sudo: required
services: 
    - docker

before_install:
    - docker build -t xobox123/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true xobox123/react-test npm test

after_success:
    - docker build -t xobox123/multi-client ./client
    - docker build -t xobox123/multi-nginx ./nginx
    - docker build -t xobox123/multi-server ./server
    - docker build -t xobox123/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push to Dockerhub
    - docker push xobox123/multi-client
    - docker push xobox123/multi-nginx
    - docker push xobox123/multi-server
    - docker push xobox123/multi-worker
